server:
  port: 8081

#database specific configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vamsimicrodb
    username: root
    password: root

#jpa specific configuartion
#spring.jpa.hibernate.ddl-auto=
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ecom-catalog

#register to eureka server
eureka:
  client:
    service-url:
      default-zone: http://eureka-registry